### ISSUE TITLE
Document orthographic and phonological inventory for esi (ipk)

### ISSUE THREAD

**Issue by dowobeha** [neural-polysynthetic-language-modelling/iyut#3]
This should be documented in sounds/esi.tsv

Use the format from sounds/ess.tsv

**Comment by kandykan** [comment]
I'd like to be assigned to this issue. I'll start working on it today. I'm pretty familiar with Iñupiaq phonology and orthography after working on the keyboard, and I also have all three volumes of Edna MacLean's grammar.

**Comment by dowobeha** [comment]
Please add esi.bib documenting where you got the info from.
